version: '3.7'

services: 
  merchandise-service:
    build: 
      context: ../
      dockerfile: Dockerfile
    hostname: 'merchandise-service'
    ports:
      - "8080:80"
  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: 'supply-service'
  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: 'emailing-service'
  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: 'employees-service'
  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: 'stock-api'
  merchandise-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: metchandiseServicePassword
      POSTGRES_DB: merchandise
    command: "-c log_statement=all"
    
    
    
    
    
    
