version: '3.7'

services: 
  merchandise-service:
    build: 
      context: ../
      dockerfile: Dockerfile
    hostname: 'merchandise-service'
    ports:
      - "5060:5060"
      - "5062:5062"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=merchandise-service-db; Port=5432; Database=merchandise-service;Username=postgres;Password=merchandiseServicePassword"
      KafkaConfiguration__BootstrapServers: "broker:29092"   
    networks:
      - ozon-network
    depends_on: 
      - merchandise-service-db
      - zookeeper
      - broker

  supply-service-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    ports:
      - "5080:5080"
      - "5082:5082"
    environment:
      DbConfiguration__ConnectionString: "Host=supply-service-db;Port=5432;Database=supply-service;Username=postgres;Password=supplyServicePassword"
      KafkaConfiguration__BootstrapServers: "broker:29092"
    networks:
     - ozon-network
    hostname: 'supply-service-api'
    depends_on:
      - supply-service-db
      - zookeeper
      - broker

  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: 'emailing-service'
    ports:
     - "8555:80"
    depends_on:
      - zookeeper
      - broker
    volumes:
      - emailing-service:/src
    networks:
      - ozon-network
  
  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: 'employees-service'
    ports:
      - "8443:80"
    environment:
      ConnectionString: "Host=employees-service-postgres-db;Port=5432;Database=employees-service;Username=postgres;Password=postgres;"
      BootstrapServers: "broker:29092" 
    depends_on:
      - employees-service-postgres-db
      - zookeeper
      - broker
    volumes:
      - employees-service:/src"
    networks: 
      - ozon-network

  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: 'stock-api'
    networks:
      - ozon-network
    ports:
      - "5070:5000"
      - "5072:5002"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=stock-api-db;Port=5432;Database=stock-api;Username=postgres;Password=stockApiPassword"
    depends_on:
      - stock-api-db
      - redis
      - supply-service-api
      - zookeeper
      - broker

  supply-service-db:
    image: postgres:latest
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supplyServicePassword
      POSTGRES_DB: supply-service
    command: "-c log_statement=all"
    networks:
      - ozon-network
    volumes:
      - supply-service-db:/var/lib/postgresql/data

  employees-service-postgres-db:
    image: postgres:latest
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees-service
    volumes:
      - employees-service-postgres-db:/var/lib/postgresql/data"
    command: "-c log_statement=all"
    networks:
      - ozon-network
      
  stock-api-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api
    command: "-c log_statement=all"
    networks:
      - ozon-network
    volumes:
      - stock-api-db:/var/lib/postgresql/data
  
  merchandise-service-db:
    image: postgres:latest
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchandiseServicePassword
      POSTGRES_DB: merchandise-service
    command: "-c log_statement=all"
    networks:
      - ozon-network
    volumes:
      - merchandise-service-db:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ozon-network

  broker:
    image: confluentinc/cp-kafka:6.2.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - ozon-network
    
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ozon-network
    hostname: redis

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - ozon-network 


networks:
  ozon-network:
     driver: bridge

volumes:
  ozon-volume:
    driver: local
  employees-service:
    driver: local
  emailing-service:
    driver: local
  merchandise-service-db:
    driver: local
  stock-api-db:
    driver: local
  supply-service-db:
    driver: local
  employees-service-postgres-db:
    driver: local
